[versions]
# https://modrinth.com/mod/architectury-api/versions
architectury = "14.0.4"

# https://parchmentmc.org/docs/getting-started
parchment-minecraft = "1.21"
parchment = "2024.07.28"

# https://projects.neoforged.net/neoforged/neoforge
neoforge = "21.3.1-beta"

# https://fabricmc.net/develop
fabric-loader = "0.16.7"
fabric-api = "0.106.1+1.21.3"

# https://modrinth.com/mod/modmenu/versions
modmenu = "12.0.0-beta.1"

# https://github.com/falkreon/Jankson/releases/latest
jankson = "1.2.3"

[libraries]
architectury-common = { module = "dev.architectury:architectury", version.ref = "architectury" }
architectury-fabric = { module = "dev.architectury:architectury-fabric", version.ref = "architectury" }
architectury-neoforge = { module = "dev.architectury:architectury-neoforge", version.ref = "architectury" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }

jankson = { module = "blue.endless:jankson", version.ref = "jankson" }
