[versions]
# https://github.com/LlamaLad7/MixinExtras/releases
mixin-extras = "0.2.0"

# https://modrinth.com/mod/architectury-api/versions
architectury = "10.0.8"

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge = "1.20.2-48.0.31"

# https://fabricmc.net/develop
fabric-loader = "0.14.23"
fabric-api = "0.90.4+1.20.2"

# https://lambdaurora.dev/tools/import_quilt.html
quilt-loader = "0.21.1"
quilted-fabric-api = "7.4.0+0.90.0-1.20.1"

# https://modrinth.com/mod/modmenu/versions
modmenu = "8.0.0"

[libraries]
architectury-common = { module = "dev.architectury:architectury", version.ref = "architectury" }
architectury-fabric = { module = "dev.architectury:architectury-fabric", version.ref = "architectury" }
architectury-forge = { module = "dev.architectury:architectury-forge", version.ref = "architectury" }
mixin-extras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin-extras" }
mixin-extras-fabric = { module = "io.github.llamalad7:mixinextras-fabric", version.ref = "mixin-extras" }
mixin-extras-forge = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixin-extras" }

forge = { module = "net.minecraftforge:forge", version.ref = "forge" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

quilt-loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt-loader" }
quilted-fabric-api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted-fabric-api" }

modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
